### ISSUE TITLE
Som administrator vil jeg kunne oprette nye film og forestillinger, så biografprogrammet er opdateret.

### ISSUE THREAD

**Issue by fiepoul** [Kinoxp-organization/KinoXP-backend#1]

**Comment by fiepoul** [comment]
Administratoren skal kunne logge ind på et sikkert admin-dashboard via brugernavn og adgangskode.

**Comment by AndreaRyholt** [comment]
Accept Kriterier:
- Oprette nye filmforestillinger
- Slette gamle filmforestillinger
- Redigerer i filmforestillinger

**Comment by hantamil** [comment]
Story points: 3
