### ISSUE TITLE
Som administrator vil jeg kunne sætte priserne for reservationer til dynamiske priser, sådan at systemet selv regner total sæde pris ud

### ISSUE THREAD

**Issue by fiepoul** [Kinoxp-organization/KinoXP-backend#3]
Når brugeren vælger et sæde, skal prisen vises for det specifikke sæde baseret på sædets placering (f.eks. cowboyrækker) eller på baggrund af hvilken type film der vises (f.eks. helaftensfilm eller 3D).
Systemet skal kunne opdatere den samlede pris dynamisk, når flere sæder vælges.

**Comment by hantamil** [comment]
Story points: 3
